# Generated by Django 4.1.7 on 2023-02-16 12:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogger",
            options={"permissions": (("is_blogger", "Blogger Permission"),)},
        ),
    ]
