# Generated by Django 4.1.7 on 2023-02-17 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_app", "0002_alter_blogger_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
